"use client"

// Define certificate templates with their styles and elements
const certificateTemplates = [
  {
    name: "Academic",
    border: "#003366",
    background: "#f5f5f5",
    elements: [
      {
        id: "title",
        type: "text",
        content: "Academic Certificate",
        x: 50,
        y: 15,
        fontSize: 32,
        fontFamily: "serif",
        color: "#003366",
        fontWeight: "bold",
        textAlign: "center",
        width: 300,
        rotation: 0,
        opacity: 1,
        shadow: {
          enabled: false,
          color: "rgba(0,0,0,0.3)",
          blur: 5,
          offsetX: 2,
          offsetY: 2,
        },
        isDragging: false,
        isVisible: true,
        zIndex: 10,
      },
      {
        id: "subtitle",
        type: "text",
        content: "Certificate of Achievement",
        x: 50,
        y: 25,
        fontSize: 18,
        fontFamily: "serif",
        color: "#555555",
        fontWeight: "normal",
        textAlign: "center",
        width: 300,
        rotation: 0,
        opacity: 1,
        isDragging: false,
        isVisible: true,
        zIndex: 11,
      },
      {
        id: "recipient-name",
        type: "text",
        content: "{ userName }",
        x: 50,
        y: 40,
        fontSize: 28,
        fontFamily: "serif",
        color: "#000000",
        fontWeight: "bold",
        textAlign: "center",
        width: 400,
        rotation: 0,
        opacity: 1,
        isDragging: false,
        isVisible: true,
        zIndex: 12,
      },
      {
        id: "accomplishment",
        type: "text",
        content: "for participating in { title }",
        x: 50,
        y: 50,
        fontSize: 18,
        fontFamily: "serif",
        color: "#555555",
        fontWeight: "normal",
        textAlign: "center",
        width: 400,
        rotation: 0,
        opacity: 1,
        isDragging: false,
        isVisible: true,
        zIndex: 13,
      },
      {
        id: "date",
        type: "text",
        content: "{ date }",
        x: 50,
        y: 65,
        fontSize: 16,
        fontFamily: "serif",
        color: "#555555",
        fontWeight: "normal",
        textAlign: "center",
        width: 200,
        rotation: 0,
        opacity: 1,
        isDragging: false,
        isVisible: true,
        zIndex: 14,
      },
      {
        id: "signature-line",
        type: "shape",
        shapeType: "rectangle",
        color: "#003366",
        x: 30,
        y: 80,
        width: 150,
        height: 2,
        rotation: 0,
        opacity: 1,
        isDragging: false,
        isVisible: true,
        zIndex: 15,
      },
      {
        id: "issuer",
        type: "text",
        content: "{ registrarName }",
        x: 30,
        y: 85,
        fontSize: 14,
        fontFamily: "serif",
        color: "#555555",
        fontWeight: "normal",
        textAlign: "center",
        width: 150,
        rotation: 0,
        opacity: 1,
        isDragging: false,
        isVisible: true,
        zIndex: 16,
      },
    ],
  },
  {
    name: "Professional",
    border: "#1a5276",
    background: "#eaf2f8",
    elements: [
      {
        id: "title",
        type: "text",
        content: "Professional Certificate",
        x: 50,
        y: 15,
        fontSize: 36,
        fontFamily: "sans-serif",
        color: "#1a5276",
        fontWeight: "bold",
        textAlign: "center",
        width: 400,
        rotation: 0,
        opacity: 1,
        shadow: {
          enabled: true,
          color: "rgba(0,0,0,0.2)",
          blur: 3,
          offsetX: 1,
          offsetY: 1,
        },
        isDragging: false,
        isVisible: true,
        zIndex: 10,
      },
      {
        id: "subtitle",
        type: "text",
        content: "This certifies that",
        x: 50,
        y: 30,
        fontSize: 18,
        fontFamily: "sans-serif",
        color: "#555555",
        fontWeight: "normal",
        textAlign: "center",
        width: 300,
        rotation: 0,
        opacity: 1,
        isDragging: false,
        isVisible: true,
        zIndex: 11,
      },
      {
        id: "recipient-name",
        type: "text",
        content: "{ userName }",
        x: 50,
        y: 40,
        fontSize: 30,
        fontFamily: "sans-serif",
        color: "#000000",
        fontWeight: "bold",
        textAlign: "center",
        width: 400,
        rotation: 0,
        opacity: 1,
        isDragging: false,
        isVisible: true,
        zIndex: 12,
      },
      {
        id: "accomplishment",
        type: "text",
        content: "has successfully completed { title }",
        x: 50,
        y: 50,
        fontSize: 18,
        fontFamily: "sans-serif",
        color: "#555555",
        fontWeight: "normal",
        textAlign: "center",
        width: 400,
        rotation: 0,
        opacity: 1,
        isDragging: false,
        isVisible: true,
        zIndex: 13,
      },
      {
        id: "date",
        type: "text",
        content: "Awarded on { date }",
        x: 50,
        y: 65,
        fontSize: 16,
        fontFamily: "sans-serif",
        color: "#555555",
        fontWeight: "normal",
        textAlign: "center",
        width: 200,
        rotation: 0,
        opacity: 1,
        isDragging: false,
        isVisible: true,
        zIndex: 14,
      },
      {
        id: "signature-line",
        type: "shape",
        shapeType: "rectangle",
        color: "#1a5276",
        x: 30,
        y: 80,
        width: 150,
        height: 2,
        rotation: 0,
        opacity: 1,
        isDragging: false,
        isVisible: true,
        zIndex: 15,
      },
      {
        id: "issuer",
        type: "text",
        content: "{ registrarName }",
        x: 30,
        y: 85,
        fontSize: 14,
        fontFamily: "sans-serif",
        color: "#555555",
        fontWeight: "normal",
        textAlign: "center",
        width: 150,
        rotation: 0,
        opacity: 1,
        isDragging: false,
        isVisible: true,
        zIndex: 16,
      },
    ],
  },
  {
    name: "Modern",
    border: "#2ecc71",
    background: "#f9f9f9",
    elements: [
      {
        id: "title",
        type: "text",
        content: "Certificate of Excellence",
        x: 50,
        y: 15,
        fontSize: 34,
        fontFamily: "Poppins",
        color: "#2ecc71",
        fontWeight: "bold",
        textAlign: "center",
        width: 400,
        rotation: 0,
        opacity: 1,
        shadow: {
          enabled: true,
          color: "rgba(0,0,0,0.1)",
          blur: 4,
          offsetX: 0,
          offsetY: 2,
        },
        isDragging: false,
        isVisible: true,
        zIndex: 10,
      },
      {
        id: "recipient-name",
        type: "text",
        content: "{ userName }",
        x: 50,
        y: 35,
        fontSize: 32,
        fontFamily: "Poppins",
        color: "#333333",
        fontWeight: "bold",
        textAlign: "center",
        width: 400,
        rotation: 0,
        opacity: 1,
        isDragging: false,
        isVisible: true,
        zIndex: 12,
      },
      {
        id: "accomplishment",
        type: "text",
        content: "has successfully completed { title } with distinction",
        x: 50,
        y: 50,
        fontSize: 18,
        fontFamily: "Poppins",
        color: "#555555",
        fontWeight: "normal",
        textAlign: "center",
        width: 500,
        rotation: 0,
        opacity: 1,
        isDragging: false,
        isVisible: true,
        zIndex: 13,
      },
      {
        id: "date",
        type: "text",
        content: "{ date }",
        x: 50,
        y: 65,
        fontSize: 16,
        fontFamily: "Poppins",
        color: "#555555",
        fontWeight: "normal",
        textAlign: "center",
        width: 200,
        rotation: 0,
        opacity: 1,
        isDragging: false,
        isVisible: true,
        zIndex: 14,
      },
      {
        id: "signature-line",
        type: "shape",
        shapeType: "rectangle",
        color: "#2ecc71",
        x: 30,
        y: 80,
        width: 150,
        height: 2,
        rotation: 0,
        opacity: 0.8,
        isDragging: false,
        isVisible: true,
        zIndex: 15,
      },
      {
        id: "issuer",
        type: "text",
        content: "{ registrarName }",
        x: 30,
        y: 85,
        fontSize: 14,
        fontFamily: "Poppins",
        color: "#555555",
        fontWeight: "normal",
        textAlign: "center",
        width: 150,
        rotation: 0,
        opacity: 1,
        isDragging: false,
        isVisible: true,
        zIndex: 16,
      },
    ],
  },
  {
    name: "Elegant",
    border: "#8e44ad",
    background: "#f5f0fa",
    elements: [
      {
        id: "title",
        type: "text",
        content: "Certificate of Achievement",
        x: 50,
        y: 15,
        fontSize: 36,
        fontFamily: "cursive",
        color: "#8e44ad",
        fontWeight: "bold",
        textAlign: "center",
        width: 400,
        rotation: 0,
        opacity: 1,
        shadow: {
          enabled: true,
          color: "rgba(142,68,173,0.2)",
          blur: 5,
          offsetX: 0,
          offsetY: 0,
        },
        isDragging: false,
        isVisible: true,
        zIndex: 10,
      },
      {
        id: "subtitle",
        type: "text",
        content: "Proudly Presented to",
        x: 50,
        y: 30,
        fontSize: 18,
        fontFamily: "cursive",
        color: "#555555",
        fontWeight: "normal",
        textAlign: "center",
        width: 300,
        rotation: 0,
        opacity: 1,
        isDragging: false,
        isVisible: true,
        zIndex: 11,
      },
      {
        id: "recipient-name",
        type: "text",
        content: "{ userName }",
        x: 50,
        y: 40,
        fontSize: 32,
        fontFamily: "cursive",
        color: "#000000",
        fontWeight: "bold",
        textAlign: "center",
        width: 400,
        rotation: 0,
        opacity: 1,
        isDragging: false,
        isVisible: true,
        zIndex: 12,
      },
      {
        id: "accomplishment",
        type: "text",
        content: "for outstanding achievement in { title }",
        x: 50,
        y: 50,
        fontSize: 18,
        fontFamily: "cursive",
        color: "#555555",
        fontWeight: "normal",
        textAlign: "center",
        width: 400,
        rotation: 0,
        opacity: 1,
        isDragging: false,
        isVisible: true,
        zIndex: 13,
      },
      {
        id: "date",
        type: "text",
        content: "{ date }",
        x: 50,
        y: 65,
        fontSize: 16,
        fontFamily: "cursive",
        color: "#555555",
        fontWeight: "normal",
        textAlign: "center",
        width: 200,
        rotation: 0,
        opacity: 1,
        isDragging: false,
        isVisible: true,
        zIndex: 14,
      },
      {
        id: "signature-line",
        type: "shape",
        shapeType: "rectangle",
        color: "#8e44ad",
        x: 30,
        y: 80,
        width: 150,
        height: 2,
        rotation: 0,
        opacity: 0.7,
        isDragging: false,
        isVisible: true,
        zIndex: 15,
      },
      {
        id: "issuer",
        type: "text",
        content: "{ registrarName }",
        x: 30,
        y: 85,
        fontSize: 14,
        fontFamily: "cursive",
        color: "#555555",
        fontWeight: "normal",
        textAlign: "center",
        width: 150,
        rotation: 0,
        opacity: 1,
        isDragging: false,
        isVisible: true,
        zIndex: 16,
      },
    ],
  },
]

// Function to create a custom template
export const createCustomTemplate = (name, elements, background, border) => {
  return {
    name: name || "Custom Template",
    border: border || "#333333",
    background: background || "#ffffff",
    elements: elements || [],
  }
}

// Export the templates
export default certificateTemplates
